Fix JSDOM interaction with querySelectorAll
The following code fails with
TypeError: e.parentElement.querySelectorAll(...).includes is not a function

```javascript
const { JSDOM } = require("jsdom");
const dom = new JSDOM(`<div>
  <span>first</span>
  <span>second</span>
<div>`);

dom.window.document.querySelector("span:has(+ span)");
```

The problem is that JSDOM uses its own patched version of
`querySelectorAll`, which returns a `NodeList`. nwsapi instead returns
an `Array`, which means that the use of querySelectorAll(...).includes
in the relative sibling selector works.